# Generated by Django 2.2 on 2020-10-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personname', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('pin', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=180)),
                ('productid', models.ImageField(upload_to='')),
            ],
        ),
    ]
