# Generated by Django 2.2 on 2020-10-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('OrderRecieved', 'OrderRecieved'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='OrderRecieved', max_length=250),
        ),
        migrations.AlterField(
            model_name='orders',
            name='productid',
            field=models.IntegerField(),
        ),
    ]
