# Generated by Django 2.2 on 2020-10-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='active_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('OrderRecieved', 'OrderRecieved'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='OrderRecieved', max_length=250),
        ),
    ]
